name: zed
description: "زد دليفري تطبيق تسوق مطاعم وبقالة واكتر ."
publish_to: 'none'

version: 1.0.1+7

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.2.1
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.1 
  geocoding_platform_interface: ^3.2.0 
  geocoding: ^4.0.0 
  geolocator: ^14.0.2
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.2 
  image_picker: ^1.0.0
  firebase_storage: ^12.3.2
  uuid: ^4.4.0 # ضيف السطر ده
  http: ^1.2.2 
  path_provider: ^2.0.0
  path: ^1.8.0
  provider: ^6.1.1
  badges: ^3.1.2
  audioplayers: ^6.0.0 # أحدث إصدار متاح
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_image_compress: 2.4.0
  intl: ^0.18.1             # أضف السطر ده
  smooth_page_indicator: ^1.2.1
  fluttertoast: ^8.2.2
  sign_in_button: ^3.2.0 # ضيف السطر ده
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  location: ^8.0.1
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.5.0
  photo_view: ^0.14.0 # تأكد من إصدار متوافق
  rxdart: ^0.27.7 
  logger: ^2.0.2
dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  # تم حذف generate: true لأنك لا تريد دعم اللغات
  assets:
    - assets/appicon.jpg
    - assets/icon.png
    - assets/sounds/new_order_sound.mp3
    - assets/google_logo.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
